
#KBUILD_CFLAGS += $(call cc-option,-mpreferred-stack-boundary=2)
#port_flags += $(call cc-option, -D__USE_LPCOPEN,)
port_flags += $(call cc-option, -D__LPC17XX__ )
port_flags += $(call cc-option, -D__CODE_RED )
#KBUILD_CFLAGS += $(tmp_flags)

